Updated Readme to avoid TypeError in Python3.5+
Converted to `int` to avoid
```
TypeError                                 Traceback (most recent call last)
      sample_rate = 16000
      frame_duration = 10  # ms
----> frame = b'\x00\x00' * (sample_rate * frame_duration / 1000)
      print('Contains speech:', vad.is_speech(frame, sample_rate))

TypeError: can't multiply sequence by non-int of type 'float'
```